# Custom Language File for Launcher Customizer

[ejs.app]
title = "Angkasa Studios Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "Welcome to Angkasa Studios Launcher"
welcomeDescription = "Angkasa Studios Launcher is a Launcher for user to play on Angkasa Studios Gamemodes."
welcomeDescCTA = "Copyright 2024 @ Angkasa Studios"
