# Custom Language File for Launcher Customizer

[ejs.app]
title = "MineMMO Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaWebsiteURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "Welcome to MineMMO Launcher"
welcomeDescription = "MineMMO is a Minecraft Survival Server that adds an MMO Styled Mechanics but doesnt remove the vanilla mechanics of the game"
welcomeDescCTA = "Copyright 2024 @ MineMMO Studios"
