name: Build

on:
  push:
    tags: [ 'v*' ] 

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash
      
      - name: Create Release (if successful build)
        uses: actions/create-release@v1  # Create a release on success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}  # Use the pushed tag for release name
          release_name: Release ${{ github.ref }}  # Custom release name (optional)
          body: |  # Provide informative release notes (optional)
            This release includes changes from commits:
            * ${{ github.sha }}

      - name: Upload Release Asset (if release created)
        uses: actions/upload-release-asset@v1  # Upload the built file if release is created
        if: steps.create-release.outputs.id  # Only upload if release exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dist/your_built_file_${{ runner.os }}.zip  # Dynamic asset name for each OS
          asset_name: your_built_file_${{ runner.os }}.zip  # Customize the uploaded file name
          asset_content_type: application/zip  # Adjust for your file type