name: Build and Upload to Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Upload Build Artifacts to Release
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist  # Modify this path if your built files are located elsewhere

      - name: Deploy to Release (Optional)
        uses: actions/upload-release-asset@v1  # Replace "..." with the upload action name (details below)
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Might require specific permissions
          file_glob: ${{ artifacts.artifacts.name }}  # Reference uploaded artifacts
          tag_name: ${{ github.ref }}  # Use the pushed tag name

**Additional Notes:**

* Choose an upload action: There are several actions that can be used for uploading files. Popular options include:
    * `actions/upload-release-asset@v1`: https://github.com/marketplace/actions/upload-to-github-release
    * `bluechip-labs/github-release-download@v2`: https://trstringer.com/github-actions-create-release-upload-artifacts/ (Consider this if you need more control over upload options)

* Update upload action details: Replace "..." in the workflow with the specific action name and configure its arguments as needed (refer to the action's documentation).
* Modify artifact path: The `path` argument in the `upload-artifact` step specifies the location of the files to upload. Update it if your built files are in a different directory.
*  Permissions for upload: Uploading to releases might require additional permissions for the GH_TOKEN. Refer to the chosen upload action's documentation for details.
*  Optional Deployment Step: The final step demonstrates how to potentially use a dedicated action for deploying the uploaded artifacts to the release page. This might involve additional configuration specifics to the chosen action.
