name: Build and Upload to Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Upload Build Artifacts to Release
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist  # Modify this path if your built files are located elsewhere

      - name: Deploy to Release (Optional)
        uses: actions/upload-release-asset@v1  # Replace "..." with the upload action name (details below)
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Might require specific permissions
          file_glob: ${{ artifacts.artifacts.name }}  # Reference uploaded artifacts
          tag_name: ${{ github.ref }}  # Use the pushed tag name