on:
  push:
    branches:
    - main

jobs:
  linux-build:
    name: Making Linux Builds
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Run Build
      run: |
        npm run dist:linux
        npm run dist
